FROM apache/airflow:2.8.1

USER root

# Installer Java 17 (recommandé pour Spark 3.x) et outils système
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk procps && \
    apt-get clean

# Définir JAVA_HOME pour PySpark
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Copier requirements.txt
COPY requirements.txt /

USER airflow

# Installer les packages Python
RUN pip install --no-cache-dir -r /requirements.txt

