global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-processing:4041']

  - job_name: 'kafka_jmx'
    static_configs:
      - targets: ['kafka:5556'] 

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

 

 